version: '3'
services:
  buildbot:
    build:
      context: ./
      dockerfile: ./master/Dockerfile.hkserver_master
    env_file:
      - ./master/db.env
    environment:
      BUILDBOT_CONFIG_DIR: config
      BUILDBOT_WORKER_PORT: 9989
    ports:
      - "8010:8010"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # network_mode: bridge
