version: "3"
services:
    buildbot:
      volumes:
        - ./master/master.cfg:/var/lib/buildbot/master.cfg
        - ./master/hkserver_ssh:/var/lib/buildbot/hkserver_ssh
    #worker:
    #  build:
    #    context: ../worker
    #    dockerfile: Dockerfile.hkserver_worker
    #  environment:
    #    BUILDMASTER: buildbot
    #    BUILDMASTER_PORT: 9989
    #    WORKERNAME: hkserver-worker
    #    WORKERPASS: password
    #    WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST