FROM        buildbot/buildbot-worker:master

# This will make apt-get install without question
ARG         DEBIAN_FRONTEND=noninteractive

USER root

# Install required npm packages
#RUN  curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
#        apt-get update && apt-get install -y -o APT::Install-Recommends=false -o APT::Install-Suggests=false \
#        nodejs \
#        git && \
#    rm -rf /var/lib/apt/lists/*

USER buildbot